# Generated by Django 5.0.2 on 2024-06-22 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasiyan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasiyan',
            name='TelNo',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
