# Generated by Django 5.0.2 on 2024-06-22 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gonderici',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TC', models.CharField(max_length=11)),
                ('Adi', models.CharField(max_length=30)),
                ('Soyadi', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TC', models.CharField(max_length=11)),
                ('AdiSoyadi', models.CharField(max_length=50)),
                ('Aciklama', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Yuksahibi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TC', models.CharField(max_length=11)),
                ('AdiSoyadi', models.CharField(max_length=50)),
                ('Aciklama', models.CharField(max_length=255)),
            ],
        ),
    ]
