# Generated by Django 5.0.2 on 2024-06-22 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gonderen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yuksahibi',
            name='Yuk',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
