# Generated by Django 5.0.2 on 2024-06-22 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gonderen', '0002_yuksahibi_yuk'),
    ]

    operations = [
        migrations.AddField(
            model_name='yuksahibi',
            name='KayitTarihi',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
